<article>
	<form action="" method="post">
		<p>Nom du site <input type="text" name="namesite" value="" /></p>
		<p>Chemin <input type="text" name="pathsite" value="<?php echo ROOT_PATH . DIRECTORY_SEPARATOR; ?>" /></p>
		<p>Url <input type="text" name="urlsite" value="" /></p>
		<input type="hidden" name="createsite" value="1" />
		<p><input type="submit" name="submit-site" value="Cr&eacute;er le site" /></p>
</form>
</article>
