<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="fr" class="no-js"> <!--<![endif]-->
	<head>
		<title>Koala Plugin</title>
		<meta charset="utf-8">
		<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/koalaplugin.css">
	</head>
	<body>
		<header>
		Koala Plugin
		</header>
		<nav>

		</nav>
	<?php echo $this->layout()->content; ?>
	<footer>

	</footer>
	</body>
</html>
